spring:     
  datasource:
    driverClassName: org.postgresql.Driver
    password: ENC(VXZp+qDfiYUZ6z6kolHBivH4vmjFA1rwNB9Wk5AjC/LPhCu4AuirCYHkl5ChOBxCjrCKB16EPUHMQhL35gVtOQ==)
    username: ecrop
    url: jdbc:postgresql://ecrop.ddns.net:5432/ecrop
    hikari:
      schema: ecrop_test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        default-schema: ecrop_test